### ISSUE TITLE
Work with Google to document how upcoming Search ranking changes affect AMP content

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#124]
This was brought up in the AC meeting today as we discussed Google Search's recent [announcement](https://webmasters.googleblog.com/2020/05/evaluating-page-experience.html).

There was clear appetite from AC members to have more clarity about the implications of these changes for AMP, in particular for a document that their constituents could share inside their own companies to help them assess the situation and inform strategy.

@nainar is apparently working on an FAQ for this. This could be a great venue to collect and list the AC's questions.

/cc @rudygalfi 

---
Champion: @sumodas 
Mentor: @tobie

**Comment by nainar** [comment]
@tobie and @sumodas to set expectations re: next steps:

Is the next step that the AC provides a list of questions that we should seed to start the FAQ? Or is it that someone on the Google end should start an FAQ based on the meeting notes?

**Comment by tobie** [comment]
My understanding from @rudygalfi was that you were working on an FAQ already, so next steps would have been to ask you to share it with the AC for input. It sounds like that might not be the case, though?

**Comment by rudygalfi** [comment]
Sorry, I think I misunderstood the approach @tobie here. At the end of the day, it would be great to work out of the same doc to suggest questions. @nainar if you can see the document with the ones you already thought of, perhaps that's where we could begin.

**Comment by nainar** [comment]
@tobie @sumodas I have started a seed document for the questions [here](https://docs.google.com/document/d/15SBggPGOT-qIVJ7fl3yqGtLrY26lTJT3NQlgeqdfnhQ/edit).

@tobie , for now you have Editor access since I didn't know what alias to share it with to give AC access. Could you share it with the appropriate alias?

The seed questions are those that I got from the meeting notes. I will let you all take the reins here since you are best suited as AMP stakeholders. 

@ampproject/tsc as FYI.

**Comment by tobie** [comment]
Sorry for the misunderstanding, both of you, and thanks for seeding that document, @nainar. Would you want me to just invite the whole of the AC to it?

**Comment by rudygalfi** [comment]
From my POV, it's great if the whole AC can contribute to it.

**Comment by nainar** [comment]
@tobie has this shared been with the AC?

**Comment by tobie** [comment]
Thanks for reminding me!

**Comment by rudygalfi** [comment]
Wanted to provide some visibility on FAQs that Google has posted in its support forum: https://support.google.com/webmasters/thread/104436075/core-web-vitals-page-experience-faqs-updated-march-2021

I will defer to the folks who opened the issue to determine if it should be closed or remain open with additional feedback.

**Comment by tobie** [comment]
Thanks @rudygalfi. As discussed in https://github.com/ampproject/meta-ac/issues/180#issuecomment-819462969, the CWV TF felt like this FAQ answered the key questions unambiguously, and as a result decided to conclude its work. The AC agreed. Closing this issue as resolved.
