### ISSUE TITLE
Champion mentoring process

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#125]
We need a way to help AC members become issue champions and to write down a process for doing so. It should be really simple:

Once you've been mentored through one issue, you can mentor someone else.

I'll be the first mentor as I've already done this work in the past here. :)

- [ ] add a blurb about this in our process doc and working doc.
- [x] figure out how to mark champions and mentors on issues.
- [ ] have an issue template for champion led-issues
- [ ] maintain a mentor roster somewhere?

**Comment by jorydotcom** [comment]
#106 Partially clears the first checkbox - it adds the stakeholder input process but doesn't capture the needs from the champion perspective
