### ISSUE TITLE
Improving communication about the AC and TSC's activity

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#14]
What can we do to improve the visibility of the TSC and the AC's activity?

- A monthly blog post with links to the minutes and highlights of the decisions made?
- A Twitter account that publishes the minutes?
- … ?

Please add your suggestions in the comments below.

**Comment by senthilp** [comment]
I would prefer a monthly blog post, highlighting on who attended the meeting, the minutes, decisions made, action items, and next steps. It doesn't have to be very formal, maybe just the notes that you take can be reviewed and published.

**Comment by tobie** [comment]
Well, I think you want to make it relevant to the community, so it can't just be the minutes of our monthly call, because hopefully that call is only fraction of our action. Also I think it's important to have both what the AC and the TSC is doing, and even maybe specific working groups.

To a degree, this falls in the community management space imho.

**Comment by wirelessjoe** [comment]
I like the idea of some kind of "post" highlighting decisions, actions, working groups, and topics soliciting community feedback to be something posted monthly or at least quarterly as a method to broaden engagement.

**Comment by tobie** [comment]
Looping @mrjoro and @pbakaus in. Thoughts/plans on the community side of things, here? How do bridge the DevRel and community management aspects?

**Comment by mrjoro** [comment]
I agree that a post summarizing what the AC has done that the community may care about over a period of time is a good idea, I'm just not sure where it should live.  We have the [blog on ampproject.org](https://www.ampproject.org/latest/blog/) where we have posted updates targeted towards a range of audiences.

For more informal updates, you could also do what the Working Groups are doing and posting [occasional updates as GitHub issues](https://github.com/search?o=desc&q=org%3Aampproject+label%3A%22Type%3A+Status+Update%22&s=created&type=Issues).  Most WGs are doing this bi-weekly.

/cc @ampproject/wg-outreach

**Comment by tobie** [comment]
I think my comment was a little bit more meta. It feels like there would be value "aggregating" the content from the various different groups into a regular "thing" so that the community can get a better sense of what's happening.

**Comment by cvazac** [comment]
I'm in favor of @tobie's
> * A Twitter account that publishes the minutes

In addition to posts detailing our contributions, ideas, recommendations, etc - rather than a prescribed cadence.

**Comment by tobie** [comment]
@cvazac would you like to take the lead on setting that up? Reach out to @ampproject/wg-outreach and figure out if you want to use a common account or a dedicated one.

**Comment by tobie** [comment]
I also like the idea of longer format blog posts at a regular cadence. Doesn't mean we can't post more often, but at least we have a baseline. Because we all know what happens when we don't. :) Would anyone be willing to figure out the specifics for blog posts?

**Comment by cvazac** [comment]
Filed https://github.com/ampproject/wg-outreach/issues/2.
