### ISSUE TITLE
Migrate old-style email working groups to new governance working groups

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/meta-ac#15]
AMP used to have largely email-based working groups that occasionally met via live hangout. These groups were content vertical-focused. The TSC's recommendation is that the AC discuss establishing new WGs under the current governance system that work toward the same goals. This would also promote inclusiveness of folks who want to engage with the project, but not through the already-established technical working groups.

Old-style working group example:
- [amp-news-publishers-wg Google group](https://groups.google.com/forum/#!forum/amp-news-publishers-wg)

**Comment by tobie** [comment]
Does this relate to #8?

**Comment by rudygalfi** [comment]
Yes, sorry for the dupe.

**Comment by tobie** [comment]
Well, it's useful additional context, so that's great.

**Comment by jorydotcom** [comment]
@tobie can this issue be closed?
