### ISSUE TITLE
amp-ac channel in amphtml.slack.com workspace

### ISSUE THREAD

**Issue by cvazac** [ampproject/meta-ac#16]
I suggest we start a private channel (#amp-ac) in the amphtml.slack.com workspace. Any thoughts on that one way or another?

(If you need an invite to that workspace, it looks like I have (everyone has?) privileges to do so, let me know)

**Comment by cvazac** [comment]
cc @ampproject/ac

**Comment by tobie** [comment]
I don't know what the practice is, here, but we probably want to keep it open, as I suspect the WG have theirs. Let's just check with @mrjoro what the practice is here, and follow along (including for naming consistency).

**Comment by tobie** [comment]
> (If you need an invite to that workspace, it looks like I have (everyone has?) privileges to do so, let me know)

I invited everyone.

**Comment by mrjoro** [comment]
The Working Group channels are open so that people who are interested can follow along/participate.  We looked into whether we could have "anyone can view, only members can post" channels, but it appears that Slack doesn't support that.

**Comment by tobie** [comment]
@mrjoro any thoughts on channel naming for consistency purposes?

**Comment by mrjoro** [comment]
I don't think there's a pattern for non-wg channels.  amp-ac sounds fine to me.

**Comment by levidurfee** [comment]
I went ahead and created #amp-ac

**Comment by tobie** [comment]
Thanks, @levidurfee. Can you announce it on the mailing list, please?
