### ISSUE TITLE
Core Web Vitals (CWV) Task Force

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#180]
### Focus

Understand how CWV measures the different flavors of AMP.

### Facilitator

@kelseyjohnson8

### Members

* @baconjulie
* @candice-womp
* @darobin
* @DavidStrauss
* @kelseyjohnson8
* @MadisonMiner
* @marissa-halpert
* @pdelgadorodriguez
* @sumodas
* @jono-alderson
* @kristoferbaxter 
* @tobie

### Deliverables

* An explainer about how CWV measures the different flavors of AMP.
* Next step recommendations for the AC

### End date

March 22

---

- [x] Members to agree on a facilitator
- [x] Members/AC to define end date
- [x] Creation approved by the AC on 2021-02-23
- [ ] Recommendations submitted to the AC on 2021-03-22

**Comment by tobie** [comment]
See also #165

**Comment by tobie** [comment]
To be clear, anyone that wants to join this task force can do so. Please add your name if you have edit permission or comment below.

**Comment by tobie** [comment]
@erwinmombay During yesterday's AC call, @kristoferbaxter suggested this AC task force might want to sync with the Perf WG. Please feel free to add yourself or someone from the WG if you think that would be useful.

**Comment by kristoferbaxter** [comment]
I've added myself to represent the Performance WG, looking forward to hearing from the wider group!

**Comment by kelseyjohnson8** [comment]
Hello! I'm putting my name in the hat for the facilitator role. Is there anyone else interested?

**Comment by tobie** [comment]
@kelseyjohnson8, as you brought this topic to the AC and as no one stepped-up to facilitate the task force when I asked during our last meeting, I think it makes sense for you to get started in that role.

It would be good for interested parties to:

1. approve Kelsey as facilitator,
2. validate the deliverables,
3. agree on an estimated date at which the task force plans to present its findings to the AC. Remember that you can always request an extension if you don't meet that deadline.

**Comment by kelseyjohnson8** [comment]
I drafted a draft doc outlining the objective of this working group, and the questions we want to answer over the next month. Everyone should have edit access. Please add questions and comments! We can go through it together on Monday. 

https://docs.google.com/document/d/1QxE1JBC4HtVtsBtjCJHqbvLRFRH_d8UPnKi6BA9t-e0/edit?usp=sharing

**Comment by kristoferbaxter** [comment]
Thanks Kelsey for agreeing to facilitate. Looking forward to hearing what the Task Force has to say.

**Comment by jono-alderson** [comment]
Have added some contentious thoughts.

*Jono Alderson *

www.jonoalderson.com
@jonoalderson <https://twitter.com/jonoalderson>
+44 (0)7990574220

*Digital strategist. Marketing technologist. Full stack developer. Keynote
speaker.*

Special Ops at Yoast <https://yoast.com/>
Founder & CTO at DaysOfTheYear.com
<http://daysoftheyear.com/>

**Comment by tobie** [comment]
Hi @kelseyjohnson8, I'd like to add the following points to your Monday agenda:

1. A reminder about our [code of conduct](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md), in particular our [pledge](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md#our-pledge) and [standards](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md#our-standards). Emotions are high on this topic and I want to make sure everyone feels safe and respected, and has a good experience participating.
2. A clarification of the scope of this task force (see my [two](https://docs.google.com/document/d/1QxE1JBC4HtVtsBtjCJHqbvLRFRH_d8UPnKi6BA9t-e0/edit?disco=AAAAH7az8qQ) [comments](https://docs.google.com/document/d/1QxE1JBC4HtVtsBtjCJHqbvLRFRH_d8UPnKi6BA9t-e0/edit?ts=60396041) on the doc).
3. Potentially splitting this task force up and/or renaming it.

**Comment by kelseyjohnson8** [comment]
Thanks @tobie , and everyone else for your comments. Proposed agenda for today. LMK if there is anything else you all would like to discuss:

-Remind members of the Code of Conduct [Tobie].
-Clarify the scope/goal of this task force. 
-Discuss modifying the task force.
-Review "Questions to Answer" section, and delegate ownership. 
-Set up next meeting.

**Comment by kelseyjohnson8** [comment]
Hi all - As we discussed after last week's working group, us publishers (@marissa-halpert @baconjulie @pdelgadorodriguez) drafted [a new document](https://docs.google.com/document/d/12pZzBgQ8m94ms9uhyzrrYXN_3qAWQExpde_YcbFh57Q/edit) that describes the problem publishers are facing around CWV and a list of the questions they are trying to answer. We'd like to take this document to the AMP Advisory Committee and ask for their recommendations on how we might be able to figure out some of these open questions. 

**Today's agenda:**
-Re-clarify the scope of this task force
-Review new document
-Align on next steps

**Comment by kelseyjohnson8** [comment]
We feel like Google's [updated FAQ](https://support.google.com/webmasters/thread/104436075?hl=en) addresses this working group's key concerns. We will report this to the AMP AC and are closing this task force.
