### ISSUE TITLE
ToDos prior to London F2F

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#23]
Room logistic:
- [x] is it required to sign an Akamai NDA prior to joining the meeting? (@cvazac)
- [x] make sure the room is video conf capable. (@cvazac)
- [x] check whether we can record some of the video conf meetings. (@cvazac)
- [ ]  setup video conf meeting for non-attendees. (@cvazac)

Lunches:
- [x] what's the deadline for catering order? (@cvazac)
- [x] create a document asking for food preference of attendees. (?)
- [x] is Akamai paying for the food? (@cvazac)
- [x] can we have coffee or something for morning/afternoon breaks?  (@cvazac)

Social:
- [x] announce post meeting open gathering on Slack. (@tobie)
- [ ] book restaurant for dinner. (@tobie)
- [x]  find out who pays for restaurant. (@tobie)

Agenda:
- [x] ask for input from contributors/users via Slack. (@tobie)
- [x] collect input from contributors/users. (@tobie)
- [x] ask for key topics from all AC members. (@tobie)
- [x] collect key topics and add them to GH project. (@tobie)

Travel:
- [x] make sure funded travelling is organized. (@tobie)

**Comment by cvazac** [comment]
- guests of Akamai will have to sign in to the building that we share, but Akamai doesn't require anything further
- the room should satisfy all of our A/V hopes and dreams, and I will rush from LHR (landing before 7a) to make sure it's setup
- we are catering breakfast (or mid morning snack) and lunch, coffee/espresso etc is available onsite
- non-Akamai corporate sponsorship of either/both would be appreciated :) 
- for catering purposes, I intend to submit final headcount (with dietary restrictions) by end of my day Thursday 3/21

**Comment by tobie** [comment]
Awesome. Thanks a lot.

**Comment by cvazac** [comment]
If you are attending the F2F in London, please add your name/dietary restrictions [here](https://docs.google.com/spreadsheets/d/1wCJ7Yz4A2GxHEX7vkeBDQHyL9DwPyb9-Lhd5lhBouTc/edit?ts=5c8fcfc6#gid=0) by Thursday 3/21.
