### ISSUE TITLE
AC F2F Agenda 2019-10-08

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#47]
# Date

October 8, 2019, during the first day of the [AMP Contributor Summit](https://amp.dev/events/amp-cs-2019/).

# Location

Location: Google office, 111 8th Avenue, New York, NY.

Enter the 8th Avenue lobby and look for people with AMP Contributor Summit badges at the Events desk near the Chase.

# Agenda

- Please add discussion topics in the comments below
- Go through [current open issues](https://github.com/ampproject/meta-ac/issues)
- Go through [project board](https://github.com/ampproject/meta-ac/projects/1)

# Schedule

Times | Topic
------ | ------------ 
8:00-9:00 | Registration in the lobby
9:00-9:30 | Housekeeping, agenda building, setup video conferencing 
9:30-10:00 | Intros
10:00-10:30 | Process
10:30-11:00 | _Coffee break_
11:00-11:30| Project board + open issues
11:30-12:00| Process update (@nainar)
12:00-1:00 | _Lunch with the community_
1:00-1:30| Support for CCPA opt-outs, see: https://github.com/ampproject/amphtml/issues/24910. (guest: @darobin).
1:30-2:00| TSC
2:00-2:30| TSC (@nainar)
2:30-3:00| Etsy architecture team (guest: Katie)
3:00-3:30|  _Coffee break_ 
3:30-4:00| SXG + WebPackaging
4:00-4:30| SXG + WebPackaging
4:30-5:00| TBD
7:30-21:00| _AC dinner_ (@sumodas to confirm)

# Hangouts

To join the video meeting, click this link: https://meet.google.com/zqj-pmms-duf
Otherwise, to join by phone, dial +1 575-914-2188 and enter this PIN: 187 740#
To view more phone numbers, click this link: https://tel.meet/zqj-pmms-duf?hl=en&hs=5

# Minutes

[Minutes]()

**Comment by tobie** [comment]
@rudygalfi Following https://github.com/ampproject/meta-tsc/issues/19, is there a slot that would work well for the TSC to meet for 30 minutes to an hour?

**Comment by tobie** [comment]
@ampproject/ac: please add agenda topics in the comments. We'll be building the final agenda at the start of the day.

**Comment by levidurfee** [comment]
Can we discuss the responsibility of the AC and what roles we the members play?

* Overall responsibility
* Individual responsibility
* How can we rely less on Tobie :)

I think a lot of us would love to help alleviate some of Tobie's tasks.

**Comment by rudygalfi** [comment]
@tobie Let me follow up with the TSC to check availability.

**Comment by wirelessjoe** [comment]
I'd propose using the 2:30-3p to VTC in a member of the Etsy architecture team, Katie, to have an informal conversation on AMP and their challenges in considering it. I think it'll be good for us to hear the perspective.

**Comment by rudygalfi** [comment]
It looks like the AMP TSC can do 1:30-2:30.

**Comment by levidurfee** [comment]
To join the video meeting, click this link: https://meet.google.com/zqj-pmms-duf
Otherwise, to join by phone, dial +1 575-914-2188 and enter this PIN: 187 740#
To view more phone numbers, click this link: https://tel.meet/zqj-pmms-duf?hl=en&hs=5

**Comment by sumodas** [comment]
FYI we have a dinner reservation for 10 at Buddakan at 7:30p.  Let me know if we need to adjust the number based on who’s here.

Buddakan
75 9th Ave, New York, NY 10011, United States
+1 212-989-6699
https://goo.gl/maps/mi4DRBP8JBnagnZ39


Best,
Sumo


—
Sumantro Das
E: sumantro.das@gmail.com
P: (845) 558-8313

**Comment by jorydotcom** [comment]
@tobie would you like me to edit this issue with a link to the notes in Google Docs?

**Comment by tobie** [comment]
Something consistant with https://github.com/ampproject/meta-ac/issues/22 would be great.
