### ISSUE TITLE
Membership in AMP AC

### ISSUE THREAD

**Issue by aghassemi** [ampproject/meta-ac#49]
Hi @ampproject/ac 

I would like to nominate myself to join AMP Advisory Committee. I was previously the facilitator of AMP UI & Accessibility Working Group and a full time contributor to AMP. 

I no longer work on AMP full time (and not at Google anymore) however I believe my background, experience and interested in a user-first Web makes me a good candidate to serve in AMP AC. If accepted to join, I will be in my personal capacity and expressing my own opinions and not of my employer (LinkedIn).

Please let me know what the next steps are and If I can provide more information for my candidacy.

Thanks!
/cc @ampproject/tsc

**Comment by tobie** [comment]
Hi @aghassemi. This is [timely](https://blog.amp.dev/2019/08/05/amp-advisory-committee-midterm-election/). :)

Mind [filling-in the form](https://forms.gle/EtvnWkLV1Ffgug126) so applications stay anonymous and everyone is on an equal footing? Thanks!
