### ISSUE TITLE
Standardization effort

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#60]
What can we extract from AMP and get the whole Web platform to benefit from by implementing in browsers?

@ampproject/ac: the goal of this issue is to define what we want to achieve in 2020 for that focus area. Please comment below with you suggestions regarding that topic.

*   **Goals:** 
*   **Outcomes:**
      *   Pieces of AMP become part of existing standards
      *   A standard spec for AMP at W3C / WHATWG
*   **Deliverables:**
      *   Have a conversation / series of conversations about standardizing AMP [#118]
*   **Ideas for Action:**
      *   Find nominee for AC election who has this interest / experience [#119]
      *   Explore / have more conversations about longer term viability of a standards effort [#120]
*   **Resources:**

**Next Steps:**

- [ ] Review issues with AC
- [ ] identify assignees for issues

[**See all Standards issues**](https://github.com/ampproject/meta-ac/projects/2?card_filter_query=label%3A%22focus+%2F+standards%22)

**Comment by jorydotcom** [comment]
Related Jamboard for Brainstorming session: https://jamboard.google.com/d/1iGDQkl-pqVR7uCrwxHnR2m__xGDRj-L-QPg0unhUjCM/viewer
