### ISSUE TITLE
Fixing URLs

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#61]
Display the publisher's URL in the address bar, not the cache's. How can we make it easier to have the right outcome?

@ampproject/ac: the goal of this issue is to define what we want to achieve in 2020 for that focus area. Please comment below with you suggestions regarding that topic.

*   **Goals:**
     *   Develop a collective position about SXG/WebPackaging
     *   Help with deployment if aligned with position
*  **Outcome:** 
     *   AMP pages have the URL that corresponds to their origin. 
*   **Deliverable:**
     *   AMP AC to write position paper [#116]
*   **Ideas for actions:**
     *   Go over the output of the ESCAPE workshop. [#117]
*   **Resources:**

**Next Steps:**

- [ ] Review issues with AC
- [ ] identify assignees for issues

[**See all URLs issues**](https://github.com/ampproject/meta-ac/projects/2?card_filter_query=label%3A%22focus+%2F+fix+URLs%22)

**Comment by KenjiBaheux** [comment]
Assuming the SXG path, the biggest issue seems to be about the amount of effort (other costs) it takes to deploy SXG versions of the AMP content. Not every publisher can roll out a DIY solution.

Support via CDN is an approach that is known to address the problem (i.e. publishers who are using CloudFlare didn't have these concerns). So, one goal could be to get more support from CDNs.

There are likely other leverage points to consider too and we could also identify how to lower the cost of a DIY solution, e.g. automating various aspects such as SXG certificate management.

**Comment by jorydotcom** [comment]
Related Jamboard for Brainstorming: https://jamboard.google.com/d/1gDMTMn_ywDkCZzHTMSdrhtrI0UTb_OrnSJ984ZdCNzI/viewer?ts=5e29bc85

**Comment by KenjiBaheux** [comment]
I did a pass on the Jamboard (blue post-it notes).

A few question ahead of the next meeting:
 - **Payment issue, and the idea that the AMP cache domain verification would perhaps be a solution**. I'm not familiar enough about the problem to formulate a reply. Background material to prepare for the meeting would be helpful.
 - **Technical questions**: having those in advance would be appreciated, I can't guarantee that I know everything about what folks might be interested in.
 - Re: "what is Apple doing wrt mobile url": I'm not aware of anything. Taking a step back, I think an interesting question to ask ourselves (and to proxy to interested parties) would be "What's ideal for developers / publishers?". Hear me out:
   - Platforms are designed for developers / publishers to create content and experiences with the hope that a lot of people find these interesting and delightful.
   - Developers / Publishers have choices (or at least strong preferences) between different platforms based on what they are allowed to do, what they can achieve, and what it means for their business.
   - In the space that interest us, there are platforms with custom proprietary formats, opinionated but open formats (i.e. come with rules/constraints), open formats where the quality of the outcome is less guaranteed.
   - What would developers, publishers prefer among the different options? Why?
   - What would they like to change, influence? 
   - Is it good for consumers?
   - What does it mean for the original question?
   - How can we help developers, publishers and consumers get what they want/need?

I hope this will seed an interesting discussion.
Stay safe!
