### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#63]
Privacy implications of the current AMP implementation.

@ampproject/ac: the goal of this issue is to define what we want to achieve in 2020 for that focus area. Please comment below with you suggestions regarding that topic.

*   **Goals:** 
*   **Outcomes:**
      *   Communication around privacy policies, changes
      *   Clearer policies for end users
      *   Caches that are not on Google / MS / Twitter servers
      *   Clarity on the caching policies 
*   **Deliverables:**
      *   Blog post on the CCPA? [#121]
*   **Ideas for Action:**
      *   Progress on SXG / Fixing URLs?
      *   Privacy policy on AMP Caches [#122]
      *   Privacy messaging [#123]
*   **Resources:**

**Next Steps:**

- [ ] Review issues with AC
- [ ] identify assignees for issues

[**See all Privacy issues**](https://github.com/ampproject/meta-ac/projects/2?card_filter_query=label%3A%22focus+%2F+privacy%22)

**Comment by jorydotcom** [comment]
Related Jamboard for brainstorming session: [https://jamboard.google.com/d/1B9MxnHysK8M_9R4xB-N0FxYM-TRvP4kRXt5SfyBYzlA/viewer](https://jamboard.google.com/d/1B9MxnHysK8M_9R4xB-N0FxYM-TRvP4kRXt5SfyBYzlA/viewer)
