### ISSUE TITLE
Be a better conduit for the requirements of the different constituencies

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#64]
@ampproject/ac: the goal of this issue is to define what we want to achieve in 2020 for that focus area. Please comment below with you suggestions regarding that topic.

*   **Goals:**
     *   Make the AC the conduit for constituencies
     *   Broadcast the needs of and results for these constituencies in order to create a virtuous cycle of input => results 
     *   Better liaison between the AC and TSC/WGs
*   **Outcome:**
      *   Input from AMP’s constituencies help drive AMP’s direction and roadmap.
*   **Deliverables:**
      *   A board where issues are tracked [#109] 
      *   A process for tracking them [#110]
          *   Input from stakeholder
          *   AC discusses it
          *   Issue is assigned to a champion
          *   Champion brings issue to TSC/relevant WG
          *   Champion drives the issue to resolution in collaboration with TSC/WG and stakeholder
          *   Issue resolution is documented
          *   Results published on the AMP blog
*   **Ideas for actions:**
      *   Work with the Outreach group to issue an annual survey (aggregate info) [#111]
      *   Source high-quality cases from AMP users (specific) [#112]
      *   Issue templates that include the process [#113]
*   **Resources**
      *   TSC and Design Meetings
      *   AMP Outreach Working Group
      *   AMP Slack & Blog (amp.dev)
      *   Design principles ([https://amp.dev/about/mission-and-vision/](https://amp.dev/about/mission-and-vision/))

**Next Steps:**

- [ ] Review issues with AC
- [ ] identify assignees for issues

[**See all Constituencies issues**](https://github.com/ampproject/meta-ac/projects/2?card_filter_query=label%3A%22focus+%2F+constituencies%22)

**Comment by tobie** [comment]
@aghassemi suggested getting more involved with roadmapping.

**Comment by jorydotcom** [comment]
Related Jamboard for brainstorming session: [https://jamboard.google.com/d/1b4scLHZtbWBbYm7Kc-xDYJaYX9iumRDWUMZkjYb7nZ4/viewer](https://jamboard.google.com/d/1b4scLHZtbWBbYm7Kc-xDYJaYX9iumRDWUMZkjYb7nZ4/viewer)
