### ISSUE TITLE
AC <-> TSC communication

### ISSUE THREAD

**Issue by tobie** [ampproject/meta-ac#7]
How do we organize good communication between the two committees?

- Have the facilitator sit on each other's meetings?
- Is the facilitator of the AC on TSC meetings enough?

**Comment by tobie** [comment]
@rudygalfi, would love your thoughts on this.

**Comment by rudygalfi** [comment]
I can bring this to the TSC.

I think it would be helpful to hear what kind of information the AC wants to provide to the TSC and/or get from the TSC. Are capturing action items in notes sufficient? What about if it's notes + members of the respective committees designated to meet F2F to provide relevant discussion context?

**Comment by tobie** [comment]
I see different aspects to this:

1. We're still in a phase in which we are figuring out the role of the AC. As such, being a passive auditor in TSC meetings can help us identify hot topics which could benefit from being further considered by the AC. Maybe reading the meeting notes is sufficient, but I'm not convinced.

2. Action items in TSC notes are good. It might be better for a point person in the TSC to turn them directly into a GH issue here, like that we have a person of contact that can provide more context if necessary. If there's a member of the AC on the TSC meeting, that person of contact could be that AC member.

3. I don't really have opinions on the AC -> TSC route yet. We should revisit once we have concrete experience of what that looks like.

**Comment by tobie** [comment]
Proposed resolution: each AC member should be responsible in turn to sit on the TSC meeting and report their findings to the AC, by filing the appropriate issues in the tracker.

Still TBD:
* how to organize the roster,
* should we change AC member at each meeting of the TSC or each meeting of the AC (so have the AC member report at the AC meeting, their month's findings).

**Comment by tobie** [comment]
Additional suggestions following discussion with the TSC:

1. We should have 2 AC members in each TSC meeting.
2. We should consider doing similar for the [design reviews](https://github.com/ampproject/amphtml/labels/Type%3A%20Design%20Review).

**Comment by tobie** [comment]
This was [approved by the AC](https://github.com/ampproject/meta-ac/blob/master/meetings/2019-03-05.md#discuss-proposed-resolution-to-tsc--ac-liaison).

@sumodas is tasked to implement:

- [ ] a rotating roster of 2 AC members to join TSC meetings and report to the AC. The rotation is synced with AC meetings.
- [ ] a (quarterly?) rotation of 1 AC member to check the design reviews agendas and alert the AC if there are design meetings we should attend.

**Comment by tobie** [comment]
Gentle ping, @sumodas.

**Comment by jorydotcom** [comment]
@tobie I propose closing this issue given that we have a new roster & mvp process for managing that now. Perhaps we also want to document it in our process or working mode docs?

**Comment by tobie** [comment]
Yup, this was left open pending the design review roster implementation. We have that now so we’re good. And yes, documenting this in the process doc sounds good. Watch out not to publicly link to documents which contain private data like emails in the process, though. The roster does.
