### ISSUE TITLE
AMP Runtime

### ISSUE THREAD

**Issue by jorydotcom** [ampproject/meta-ac#84]
At the AMP AC meeting on Monday ([see notes][1]), some AC members reported issues with size of the AMP runtime. Is this a known issue? If so, where is it tracked?

[1]: https://github.com/ampproject/meta-ac/pull/79/commits/1f68844ac31ebf6bb421a0163fe6e55983f4aeaf

(👋 quick intro: I'm Jory and I'll be helping @tobie with AMP AC facilitation this year. excited to meet you all at some point!)

**Comment by rudygalfi** [comment]
@tobie Initiated transfer. I didn't know that was a thing, but now I do. :)

**Comment by tobie** [comment]
> @tobie Initiated transfer. I didn't know that was a thing, but now I do. :)

Oh, boy. What did I do!!? :D
